--
-- PostgreSQL database dump
--

\restrict PbOwR74QQ5mJA85x7bHPqY4QsplVLdn7CCRPtdKZ3RyPynfzAAg0wZ1NKrcuQul

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-08-12 00:29:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16452)
-- Name: assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assignments (
    assignment_id integer NOT NULL,
    assignment_course text NOT NULL,
    assignment_details text NOT NULL,
    assignment_deadline text NOT NULL,
    assignment_mark double precision NOT NULL,
    assignment_status text NOT NULL,
    assignment_title text
);


ALTER TABLE public.assignments OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16474)
-- Name: assignments_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assignments ALTER COLUMN assignment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16502)
-- Name: course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course (
    course_id integer NOT NULL,
    course_name text
);


ALTER TABLE public.course OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16510)
-- Name: course_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16475)
-- Name: marksheet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marksheet (
    student_name text NOT NULL,
    course_name text NOT NULL,
    mark double precision NOT NULL,
    feedback text NOT NULL,
    mark_id integer NOT NULL
);


ALTER TABLE public.marksheet OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16490)
-- Name: marksheet_mark_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marksheet ALTER COLUMN mark_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marksheet_mark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16534)
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    session_id integer NOT NULL,
    user_id integer NOT NULL,
    session_token text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16533)
-- Name: sessions_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.sessions_session_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sessions_session_id_seq OWNER TO postgres;

--
-- TOC entry 4952 (class 0 OID 0)
-- Dependencies: 227
-- Name: sessions_session_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.sessions_session_id_seq OWNED BY public.sessions.session_id;


--
-- TOC entry 223 (class 1259 OID 16491)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_name text NOT NULL,
    user_role text NOT NULL,
    user_password text,
    user_email text
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16501)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4775 (class 2604 OID 16537)
-- Name: sessions session_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions ALTER COLUMN session_id SET DEFAULT nextval('public.sessions_session_id_seq'::regclass);


--
-- TOC entry 4937 (class 0 OID 16452)
-- Dependencies: 219
-- Data for Name: assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assignments (assignment_id, assignment_course, assignment_details, assignment_deadline, assignment_mark, assignment_status, assignment_title) FROM stdin;
1	Web Development	Create a student management system using Next.js and ASP.NET Core Web API.	2026-08-25	100	Published	Build a Student Management System
\.


--
-- TOC entry 4943 (class 0 OID 16502)
-- Dependencies: 225
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.course (course_id, course_name) FROM stdin;
1	Android Development
2	Linux
\.


--
-- TOC entry 4939 (class 0 OID 16475)
-- Dependencies: 221
-- Data for Name: marksheet; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marksheet (student_name, course_name, mark, feedback, mark_id) FROM stdin;
Tanvir AHmed	operating system	80.9	keep it up	1
\.


--
-- TOC entry 4946 (class 0 OID 16534)
-- Dependencies: 228
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (session_id, user_id, session_token, created_at, expires_at, revoked) FROM stdin;
7	1002	1c0bd8ea-04e3-4d2c-bece-18a15bcf52e1	2026-08-11 23:39:28.192921	2026-08-12 00:39:28.192921	t
8	1002	38efb3c7-6e42-40ed-8d97-269aff92dd01	2026-08-11 23:40:12.552601	2026-08-12 00:40:12.552602	t
\.


--
-- TOC entry 4941 (class 0 OID 16491)
-- Dependencies: 223
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, user_name, user_role, user_password, user_email) FROM stdin;
1002	Tanvir Ahmed	Student	$2a$11$LD84B/aV2kYjer0kcsvafe2k.j5TLCJpodJJoNbvym0O2nPECSBTO	tanvir@gmail.com
\.


--
-- TOC entry 4953 (class 0 OID 0)
-- Dependencies: 220
-- Name: assignments_assignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assignments_assignment_id_seq', 1, true);


--
-- TOC entry 4954 (class 0 OID 0)
-- Dependencies: 226
-- Name: course_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_course_id_seq', 2, true);


--
-- TOC entry 4955 (class 0 OID 0)
-- Dependencies: 222
-- Name: marksheet_mark_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marksheet_mark_id_seq', 1, true);


--
-- TOC entry 4956 (class 0 OID 0)
-- Dependencies: 227
-- Name: sessions_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_session_id_seq', 8, true);


--
-- TOC entry 4957 (class 0 OID 0)
-- Dependencies: 224
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1002, true);


--
-- TOC entry 4778 (class 2606 OID 16466)
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (assignment_id);


--
-- TOC entry 4784 (class 2606 OID 16509)
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (course_id);


--
-- TOC entry 4780 (class 2606 OID 16489)
-- Name: marksheet marksheet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marksheet
    ADD CONSTRAINT marksheet_pkey PRIMARY KEY (mark_id);


--
-- TOC entry 4786 (class 2606 OID 16548)
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (session_id);


--
-- TOC entry 4788 (class 2606 OID 16550)
-- Name: sessions sessions_session_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_session_token_key UNIQUE (session_token);


--
-- TOC entry 4782 (class 2606 OID 16500)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4789 (class 2606 OID 16551)
-- Name: sessions fk_sessions_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2026-08-12 00:29:05

--
-- PostgreSQL database dump complete
--

\unrestrict PbOwR74QQ5mJA85x7bHPqY4QsplVLdn7CCRPtdKZ3RyPynfzAAg0wZ1NKrcuQul

